[directory]
style = 'blue bold'
read_only = " "

[cmd_duration]
min_time = 500
format = "took [$duration](bold purple)"

[lua]
style = 'cyan bold'

[aws]
symbol = "  "

[buf]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "
style = 'yellow'

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "
style= 'green'

[package]
symbol = " "

[rust]
symbol = " "
